import '../../app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Seed Admin - IFSul',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1>Admin Page</h1>
        </div>
      </body>
    </html>
  )
}
